import React from 'react'

const Environment: React.FC = () => {
  return (
    <div className="min-h-screen bg-warm-50 py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-gradient mb-6 leading-normal" style={{ paddingBottom: '0.1em' }}>
            Interactive AI-Generated Environments
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Experience dynamic GUI testing environments generated by AI, providing unique and fair evaluation scenarios for every agent test. Explore our comprehensive test cases that demonstrate the challenges agents face in these environments.
          </p>
          <div className="mt-6 flex justify-center items-center space-x-2">
            <div className="w-2 h-2 bg-warm-500 rounded-full"></div>
            <div className="w-2 h-2 bg-coral-500 rounded-full"></div>
            <div className="w-2 h-2 bg-gold-500 rounded-full"></div>
          </div>
        </div>

        {/* Placeholder Content */}
        <div className="card max-w-4xl mx-auto">
          <div className="text-center py-16">
            <div className="w-24 h-24 bg-coral-100 rounded-full flex items-center justify-center mx-auto mb-6">
              <svg className="w-12 h-12 text-coral-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
            </div>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Interactive Demo Environment
            </h2>
            <p className="text-gray-600 mb-8 max-w-md mx-auto">
              Explore our AI-generated GUI environments where each evaluation creates a unique testing scenario, ensuring agents demonstrate genuine problem-solving capabilities.
            </p>
            <div className="animate-pulse-warm">
              <p className="text-coral-600 font-medium">
                Dynamic environments that adapt to your testing needs!
              </p>
            </div>
          </div>

          {/* Preview Section */}
          <div className="border-t border-gray-200 pt-8 mt-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">
              Environment Features:
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 bg-warm-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <svg className="w-5 h-5 text-warm-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900 mb-1">Dynamic GUI Generation</h4>
                  <p className="text-sm text-gray-600">
                    AI creates unique interfaces, layouts, and interaction patterns for each evaluation session
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 bg-coral-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <svg className="w-5 h-5 text-coral-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900 mb-1">Real-time Interaction</h4>
                  <p className="text-sm text-gray-600">
                    Live testing scenarios where agents can click, type, navigate, and manipulate interface elements
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 bg-gold-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <svg className="w-5 h-5 text-gold-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900 mb-1">Variable Complexity</h4>
                  <p className="text-sm text-gray-600">
                    Environments adapt in complexity based on agent capabilities and evaluation requirements
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-4">
                <div className="w-10 h-10 bg-warm-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <svg className="w-5 h-5 text-warm-600" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                  </svg>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900 mb-1">Multi-step Tasks</h4>
                  <p className="text-sm text-gray-600">
                    Complex scenarios requiring agents to complete sequences of actions to achieve goals
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Environment Types */}
          <div className="border-t border-gray-200 pt-8 mt-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">
              Environment Categories:
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="text-center p-4 bg-warm-50 rounded-lg">
                <div className="w-12 h-12 bg-warm-100 rounded-lg flex items-center justify-center mx-auto mb-3">
                  <svg className="w-6 h-6 text-warm-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                  </svg>
                </div>
                <h4 className="font-medium text-gray-900 mb-2">Web Applications</h4>
                <p className="text-sm text-gray-600">
                  Dynamic web interfaces with forms, navigation, and interactive components
                </p>
              </div>

              <div className="text-center p-4 bg-coral-50 rounded-lg">
                <div className="w-12 h-12 bg-coral-100 rounded-lg flex items-center justify-center mx-auto mb-3">
                  <svg className="w-6 h-6 text-coral-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />
                  </svg>
                </div>
                <h4 className="font-medium text-gray-900 mb-2">Desktop Apps</h4>
                <p className="text-sm text-gray-600">
                  Native application interfaces with complex workflows and state management
                </p>
              </div>

              <div className="text-center p-4 bg-gold-50 rounded-lg">
                <div className="w-12 h-12 bg-gold-100 rounded-lg flex items-center justify-center mx-auto mb-3">
                  <svg className="w-6 h-6 text-gold-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z" />
                  </svg>
                </div>
                <h4 className="font-medium text-gray-900 mb-2">Mobile Interfaces</h4>
                <p className="text-sm text-gray-600">
                  Touch-optimized interfaces with gestures and responsive layouts
                </p>
              </div>
            </div>
          </div>

          {/* Test Cases Section */}
          <div className="border-t border-gray-200 pt-8 mt-8">
            <div className="text-center mb-8">
              <h3 className="text-2xl font-bold text-gray-900 mb-4">Sample Test Cases</h3>
              <p className="text-gray-600 max-w-2xl mx-auto">
                Explore the types of challenges agents face in our AI-generated environments. Each test case is designed to evaluate specific capabilities while ensuring fair assessment through dynamic generation.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow bg-white">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs bg-warm-100 text-warm-700 px-2 py-1 rounded font-medium">Web Form</span>
                  <div className="flex space-x-1">
                    <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Complex</span>
                  </div>
                </div>
                <h4 className="font-semibold text-gray-900 mb-2">Web Form Automation</h4>
                <p className="text-sm text-gray-600 mb-4">Complex form filling with validation, dynamic elements, and multi-step submission processes</p>
                <div className="space-y-2">
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Form validation handling
                  </div>
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Dynamic element interaction
                  </div>
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Error state management
                  </div>
                </div>
              </div>

              <div className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow bg-white">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs bg-coral-100 text-coral-700 px-2 py-1 rounded font-medium">Navigation</span>
                  <div className="flex space-x-1">
                    <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Advanced</span>
                  </div>
                </div>
                <h4 className="font-semibold text-gray-900 mb-2">Multi-step Navigation</h4>
                <p className="text-sm text-gray-600 mb-4">Navigate through complex application workflows with state preservation and conditional routing</p>
                <div className="space-y-2">
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Complex workflow navigation
                  </div>
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    State preservation
                  </div>
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Conditional routing
                  </div>
                </div>
              </div>

              <div className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow bg-white">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-xs bg-gold-100 text-gold-700 px-2 py-1 rounded font-medium">Data</span>
                  <div className="flex space-x-1">
                    <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">Expert</span>
                  </div>
                </div>
                <h4 className="font-semibold text-gray-900 mb-2">Data Extraction</h4>
                <p className="text-sm text-gray-600 mb-4">Extract and process data from various UI elements with accuracy validation</p>
                <div className="space-y-2">
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Multi-source data parsing
                  </div>
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Accuracy validation
                  </div>
                  <div className="flex items-center text-xs text-gray-500">
                    <svg className="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    Format standardization
                  </div>
                </div>
              </div>
            </div>

            <div className="text-center">
              <p className="text-sm text-gray-500 mb-4">
                <strong>527 total test cases</strong> across Web, Desktop, and Mobile environments
              </p>
              <div className="inline-flex items-center space-x-4 text-sm text-gray-600">
                <div className="flex items-center">
                  <div className="w-3 h-3 bg-warm-500 rounded-full mr-2"></div>
                  Web Applications (312)
                </div>
                <div className="flex items-center">
                  <div className="w-3 h-3 bg-coral-500 rounded-full mr-2"></div>
                  Desktop Apps (134)
                </div>
                <div className="flex items-center">
                  <div className="w-3 h-3 bg-gold-500 rounded-full mr-2"></div>
                  Mobile Interfaces (81)
                </div>
              </div>
            </div>
          </div>

          {/* Tech Stack Preview */}
          <div className="border-t border-gray-200 pt-8 mt-8">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">
              Generation Technology:
            </h3>
            <div className="flex flex-wrap gap-3 justify-center">
              <span className="px-3 py-1 bg-warm-100 text-warm-700 rounded-full text-sm font-medium">
                AI-Powered Generation
              </span>
              <span className="px-3 py-1 bg-coral-100 text-coral-700 rounded-full text-sm font-medium">
                Real-time Rendering
              </span>
              <span className="px-3 py-1 bg-gold-100 text-gold-700 rounded-full text-sm font-medium">
                State Management
              </span>
              <span className="px-3 py-1 bg-warm-100 text-warm-700 rounded-full text-sm font-medium">
                Event Simulation
              </span>
              <span className="px-3 py-1 bg-coral-100 text-coral-700 rounded-full text-sm font-medium">
                Cross-platform Support
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Environment